// Copies the core premises (the text between the two "---" rules in
// prompts/core-premises.md) into a TypeScript module the app imports.
// Run automatically before dev, build, typecheck and test.
// With --check, exits 1 if the generated file is out of date (used in CI).
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const source = path.join(here, "..", "..", "prompts", "core-premises.md");
const target = path.join(here, "..", "lib", "engine", "core-premises.generated.ts");

if (!existsSync(source)) {
  // A build that only sees web/ (for example a host that excludes files outside it) keeps the
  // committed copy. CI runs --check against the real file, so the copy cannot drift.
  if (existsSync(target)) {
    console.warn("prompts/core-premises.md not found; keeping the committed core premises.");
    process.exit(0);
  }
  console.error("prompts/core-premises.md not found and no generated copy exists.");
  process.exit(1);
}

const md = readFileSync(source, "utf8").replace(/\r\n/g, "\n");
const parts = md.split(/\n---\n/);
if (parts.length < 3) {
  console.error("prompts/core-premises.md must contain the prompt between two '---' lines.");
  process.exit(1);
}
const prompt = parts[1].trim();
const output =
  "// Generated by scripts/sync-prompt.mjs from prompts/core-premises.md. Do not edit by hand.\n" +
  `export const CORE_PREMISES = ${JSON.stringify(prompt)};\n`;

if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current !== output) {
    console.error("lib/engine/core-premises.generated.ts is out of date. Run: npm run sync:prompt");
    process.exit(1);
  }
  console.log("Core premises are in sync.");
} else {
  writeFileSync(target, output);
  console.log(`Synced core premises (${prompt.length} characters).`);
}
